name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Golang api
        run: |
          cd api
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app main.go

      - name: Build web
        run: |
          cd web
          npm install && npm run build

      - name: Build the Docker image
        run: |
          cd api
          echo ${{secrets.ENVFILE}} > .env
          docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}} registry.cn-shanghai.aliyuncs.com
          docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/fifsky/gostruct
          docker push registry.cn-shanghai.aliyuncs.com/fifsky/gostruct
          cd ../web
          docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/fifsky/gostruct-web
          docker push registry.cn-shanghai.aliyuncs.com/fifsky/gostruct-web

      - name: Pull docker and restart
        run: |
          curl -s "https://hook.fifsky.com/?token=${{secrets.WEBHOOK_TOKEN}}&script=go-struct"

      - name: Dingtalk message
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK}}
          type: markdown
          content: |
            ## Github Action
            > genstruct deploy successful
            > ^_^